#! /bin/sh

# system init
/usr/lib/geoclue-2.0/demos/agent & # geo for redshift

# keyboard shortcuts
killall sxhkd
sxhkd &

# bar
killall polybar
polybar top &

# compositor
picom &

# wallpapers
nitrogen --restore

# bspwm configuration
bspc monitor -d I II III IV V VI VII 

bspc config border_width         3
bspc config window_gap          4
bspc config border_radius 15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config directional_focus_tightness low

bspc rule -a kitty-floating state=floating rectangle=1100x700+730+190
bspc rule -a qalc state=floating rectangle=300x500+1500+290
bspc rule -a updates-splash state=floating rectangle=1100x700+730+190
bspc rule -a ranger state=floating rectangle=1100x700+730+190
bspc rule -a kotatogram-desktop desktop=^2

# cursor, keyboard layout, numlock
xsetroot -cursor_name left_ptr &
setxkbmap -model pc105 -layout us,ru -variant qwerty -option grp:win_space_toggle
numlockx on
bluetoothctl power on

# applications
sleep 10

killall kdeconnect-indi
kdeconnect-indicator &

element-desktop --hidden &

kotatogram-desktop -startintray &

