#!/usr/bin/env sh
#
# A rofi powered menu to execute power related action.
# Uses: amixer mpc poweroff reboot rofi ./rofi-prompt

power_off=''
reboot=''
# lock=''
suspend='鈴'
# log_out=''

# add other modes
chosen=$(printf '%s;%s;%s\n' "$suspend" "$reboot" "$power_off" \
    | rofi -theme '~/.config/rofi/gruvbox-powermenu.rasi' \
           -dmenu \
           -sep ';' \
           -selected-row 2)

case "$chosen" in
    "$power_off")
        poweroff
        ;;

    "$reboot")
        reboot
        ;;

    "$lock")
        # TODO Add your lockscreen command.
        ;;

    "$suspend")
		~/.scripts/volume-control mute
		systemctl suspend
        ;;

    "$log_out")
        # TODO Add your log out command.
        ;;

    *) exit 1 ;;
esac
